apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: heinens
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
        - name: api
          image: heinens-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
          volumeMounts:
            - name: sqlite-storage
              mountPath: /data
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc
